# Generated by Django 4.2 on 2023-04-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100)),
                ('empname', models.CharField(max_length=100)),
                ('empemail', models.EmailField(max_length=254)),
                ('empcontact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.IntegerField(db_column='patid')),
                ('patname', models.CharField(blank=True, db_column='patname', max_length=100, null=True)),
                ('patge', models.IntegerField(db_column='patage')),
                ('emp', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_register.emp')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
