# Generated by Django 4.2 on 2023-05-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='consultFees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Genbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genid', models.IntegerField(blank=True, null=True)),
                ('genname', models.CharField(max_length=100)),
                ('genamt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genamtpaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genamtdue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genlink', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_register.patient')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
